trigger:
  - release/*
  - hotfix/*
  
pool:
  vmImage: ubuntu-20.04

variables:
  FEED_ID: 61101818-286e-47e5-b86b-ef800ee02eea
  # Don't forget add trailing slash ('/').
  BUILD_DEST_PATH: dist/nusantara-admin
  APM_URL: https://apm.bhisma.cloud/
  # NPM_CACHE_FEED: e09e6f3d-7f3b-43d4-8f43-f50424bd8131

resources:
  repositories:
    - repository: templates
      type: git
      name: Operations/pipeline-templates

jobs:
  - job: unit_test
    displayName: Run Unit Test
    steps:
      # https://dev.azure.com/gramediadigital/Operations/_git/pipeline-templates?path=%2Fweb%2Funit_test.yml
      - template: web/unit_test.yml@templates
        parameters:
          feedId: $(FEED_ID)
          testArgs: ''

      # - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
      #   displayName: Restore and save cache from Azure Artifact
      #   inputs:
      #     keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
      #     targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
      #     vstsFeed: '$(NPM_CACHE_FEED)'
      #     platformIndependent: true
      #     alias: nusantara-admin

  - job: build_prod
    displayName: Build & Packaging PROD
    dependsOn: unit_test
    condition: |
      and(
        succeeded(),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    steps:
      # https://dev.azure.com/gramediadigital/Operations/_git/pipeline-templates?path=%2Fweb%2Fbuild.yml
      - template: web/build.yml@templates
        parameters:
          appEnv: production
          feedId: $(FEED_ID)
          buildPath: $(BUILD_DEST_PATH)
          envVars: 'APM_NAME=nus-admin APM_ACTIVE=True APM_ENVIRONMENT=production APM_URL=$(APM_URL)'

      # - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
      #   displayName: Restore and save cache from Azure Artifact
      #   inputs:
      #     keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
      #     targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
      #     vstsFeed: '$(NPM_CACHE_FEED)'
      #     platformIndependent: true
      #     alias: nusantara-admin

      # - task: Npm@1
      #   displayName: Install App Dependencies
      #   inputs:
      #     verbose: false
      #   condition: ne(variables['CacheRestored-nusantara-admin'], 'true')

  # Staging Build
  - job: build_staging
    displayName: Build & Packaging STAGING
    dependsOn: unit_test
    condition: |
      and(
        succeeded(),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    steps:
      - template: web/build.yml@templates
        parameters:
          feedId: $(FEED_ID)
          buildPath: $(BUILD_DEST_PATH)
          envVars: 'APM_NAME=nus-admin APM_ACTIVE=False APM_ENVIRONMENT=staging APM_URL=$(APM_URL)'
