trigger:
  - release/*
  - hotfix/*
  - master

pool:
  vmImage: ubuntu-20.04

variables:
  - group: nusantara-web-pipeline-build
  - group: Aws-Programatic

  # Don't forget add trailing slash ('/').
  - name: BUILD_DEST_PATH
    value: dist/nusantara-admin

  - name: APM_NAME
    value: web-admin

  - name: DOCKER_REPO
    value: gramedia/nginx

  # runtime variables, automatically defined by agent when pipeline running
  - name: IS_NON_MASTER_BRANCH
    value: $[ne(variables['Build.SourceBranch'], 'refs/heads/master')]

resources:
  repositories:
    - repository: templates
      type: git
      name: Operations/pipeline-templates

jobs:
  - job: unit_test
    displayName: Run Unit Test
    steps:
      # https://dev.azure.com/gramediadigital/Operations/_git/pipeline-templates?path=%2Fweb%2Funit_test.yml
      - template: web/unit_test.yml@templates
        parameters:
          feedId: $(FEED_ID)
          testArgs: ''

  - job: build_prod
    dependsOn: unit_test
    pool:
      name: docker-agent
    displayName: Build & Packaging PROD
    condition: |
      and(
        succeeded(),
        eq('True', variables.IS_NON_MASTER_BRANCH),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    steps:
      # https://dev.azure.com/gramediadigital/Operations/_git/pipeline-templates?path=%2Fweb%2Fbuild.yml
      - template: web/build.yml@templates
        parameters:
          appEnv: production
          feedId: $(FEED_ID)
          buildPath: $(BUILD_DEST_PATH)
          envVars: 'APM_NAME=$(APM_NAME) APM_ACTIVE=True APM_ENVIRONMENT=production APM_URL=$(APM_URL)'

      - task: Bash@3
        displayName: Get App Version
        inputs:
          targetType: 'inline'
          script: |
            export APP_VERSION="admin-$(Build.SourceBranchName)"
            
            echo "Current version of app is $APP_VERSION"

            # Set pipeline variable "DOCKER_TAG"
            echo "##vso[task.setvariable variable=DOCKER_TAG]$APP_VERSION"
            echo $APP_VERSION | tee VERSION

      - task: Docker@2
        displayName: Docker Build
        inputs:
          repository: $(DOCKER_REPO)
          command: build
          tags: |
            $(Build.BuildId)

      - task: ECRPushImage@1
        displayName: Docker Push to ECR (Version Tags)
        inputs:
          awsCredentials: $(AWS_CREDENTIAL_NAME)
          regionName: $(AWS_REGION)
          sourceImageName: $(DOCKER_REPO)
          sourceImageTag: '$(Build.BuildId)'
          repositoryName: $(DOCKER_REPO)
          pushTag: $APP_VERSION
          autoCreateRepository: true

  # Staging Build
  - job: build_staging
    # dependsOn: build_prod
    pool:
      name: docker-agent
    displayName: Build & Packaging STAGING
    condition: |
      and(
        succeeded(),
        eq('True', variables.IS_NON_MASTER_BRANCH),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    steps:
      - template: web/build.yml@templates
        parameters:
          feedId: $(FEED_ID)
          buildPath: $(BUILD_DEST_PATH)
          envVars: 'APM_NAME=$(APM_NAME) APM_ACTIVE=False APM_ENVIRONMENT=staging APM_URL=$(APM_URL)'

      - task: Bash@3
        displayName: Get App Version
        inputs:
          targetType: 'inline'
          script: |
            export APP_VERSION="admin-$(Build.SourceBranchName)"
            
            echo "Current version of app is $APP_VERSION"

            # Set pipeline variable "DOCKER_TAG"
            echo "##vso[task.setvariable variable=DOCKER_TAG]$APP_VERSION"
            echo $APP_VERSION | tee VERSION

      - task: Docker@2
        displayName: Docker Build
        inputs:
          repository: $(DOCKER_REPO)
          command: build
          tags: |
            $(Build.BuildId)

      - task: ECRPushImage@1
        displayName: Docker Push to ECR (Version Tags)
        inputs:
          awsCredentials: $(AWS_CREDENTIAL_NAME)
          regionName: $(AWS_REGION)
          sourceImageName: $(DOCKER_REPO)
          sourceImageTag: '$(Build.BuildId)'
          repositoryName: $(DOCKER_REPO)
          pushTag: $APP_VERSION
          autoCreateRepository: true
