events { } # don't care what's here

http {
    include    /etc/nginx/mime.types;
    access_log /dev/stdout;
    error_log  /dev/stdout info;

    add_header 'Access-Control-Allow-Origin' '*' always;
    # add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD, PUT, PATCH, DELETE';
    # add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,User-Agent,X-User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';

    upstream iam { server iam:8000; }
    # upstream catalog { server catalog_api:8000; }
    # upstream fulfillment { server fulfillment_api:8000; }
    # upstream cms { server cms_api:8000; }

    server {
        listen 80;
        location /api/iam {
            proxy_pass "http://iam";
            proxy_set_header Host $host;
        }
    }
}
