events { } # don't care what's here

http {
  types {
    module;
  }
    include    /etc/nginx/mime.types;
    access_log /dev/stdout;
    error_log  /dev/stdout info;

    # Expires map for caching resources
    map $sent_http_content_type $expires {
      default                    off;
      text/html                  epoch;
      text/css                   max;
      application/javascript     max;
      ~image/                    max;
    }

    add_header 'Access-Control-Allow-Origin' '*' always;
    # add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD, PUT, PATCH, DELETE';
    # add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,User-Agent,X-User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';

    # upstream iam { server iam:8000; }
    # upstream catalog { server catalog_api:8000; }
    # upstream fulfillment { server fulfillment_api:8000; }
    # upstream cms { server cms_api:8000; }

    # Browser preferred language detection
    map $http_accept_language $accept_language {
      ~*^en en;
      ~*^id id;
    }

    server {
        listen 80;
        root         /usr/share/nginx/html;
        # location /api/iam {
        #     proxy_pass "http://iam";
        #     proxy_set_header Host $host;
        # }

        # Set cache expires from the map we defined.
        expires $expires;

        # Security. Don't send nginx version in Server header.
        server_tokens off;

        # Fallback to default language if no preference defined by browser
        if ($accept_language ~ "^$") {
          set $accept_language "en";
        }

        # Redirect "/" to Angular app in browser's preferred language
        rewrite ^/$ /$accept_language permanent;

        # Everything under the Angular app is always redirected to Angular in the correct language
        location ~ ^/(en|id) {
          try_files $uri /$1/index.html?$args;

          # Add security headers from separate file
          # include /etc/nginx/security-headers.conf;
        }

    }
}
