import { Component, ViewChild } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ErrorResult, getSlugFromHref } from '@nusantara/core';
import { OrderService, ShipmentService } from '@nusantara/services';
import { drf, order, OrderStatusType } from '@nusantara/models';
import { 
  TransportToCounterSelectionModalComponent, 
  PickupDownloadShippingModalComponent, 
  SetPickUpServiceComponent, 
  PickupServiceInfoModalComponent,
  InputAwbModalComponent, 
  DeliverToCounterAutogeneratedAwbComponent,
  DeliverToCounterManualInputAwbComponent,
  ActivityTrackingModalComponent,  
} from './modals';

@Component({
  selector: 'nus-order-detail',
  template: `  
    <div class="wrapper">
      <ng-container *ngFor="let children of orderDetailData.children">
        <table class="order-status">
          <tbody>
            <tr>
              <td>
                <div class="body-2">Status</div>
                <div class="subheading-2">{{ (orderDetailData.status ? orderDetailData.status : '-') | titlecase }}</div>
              </td>
              <td>
                <div class="body-2">Logistic</div>
                <div class="subheading-2">
                  <ng-container *ngIf="children.data[0]?.shippingMethod">{{ children.data[0].shippingMethod }}</ng-container>
                </div>
              </td>
              <td>
                <div class="body-2">AWB</div>
                <div class="subheading-2">
                  {{ getConnote(children.data[0])? getConnote(children.data[0]) : '-' }}
                </div>
              </td>
              <td>
                <ng-container *ngIf="isManualTransfer(orderDetailData)">
                  <div class="body-2">Warehouse</div>
                  <div class="subheading-2">
                    {{ children.warehouse.name }}
                  </div>
                </ng-container>
              </td>
            </tr>
            <tr>
              <td colspan="4">
                <span class="button-status-action">
                  <nus-milestone [steps]="['ready', 'ship', 'complete']" [current]="currentMilestone"></nus-milestone>

                  <ng-container *ngIf="isShippableOrder">
                    <button *ngIf="orderDetailData.status === 'unpaid'" type="button" class="control" disabled>Ready</button>
                    <button *ngIf="orderDetailData.status === 'paid'" type="button" class="control">Ready</button>
                    <button *ngIf="orderDetailData.status === 'ready'" type="button" class="control">Ship</button>
                    <button *ngIf="orderDetailData.status === 'shipped'" type="button" class="control">Complete</button>

                    <!-- <button type="button" class="control secondary" 
                      (click)="activityTracking.open()">
                      View Progress
                      </button>
                    -->
                  </ng-container>

                  <button class="download-button control secondary"
                    [disabled]="!getConnote(children.data[0])" 
                    (click)="printConnote(children.data[0].shipmentHistory.shippingLabelUrl)">
                    Download Shipping Label
                  </button>
                </span>
              </td>
            </tr>
          </tbody>
        </table>

        <table class="product-list">
          <tbody>
          <tr>
            <td colspan="5">
              <h3 class="heading-1">Product</h3>
            </td>
          </tr>
          <ng-container *ngFor="let data of children.data">
            <tr *ngFor="let lineItems of data.lineItems">
              <td>
                <div *ngIf="lineItems.product.image; else noImage">
                  <img [src]="lineItems.product.image" alt="Product Image">
                </div>
                <ng-template #noImage>
                  <img class="no-image" src="/assets/no-image_en.png" alt="Product Image">
                </ng-template>
              </td>
              <td>
                <div class="subheading-2">
                  {{ lineItems.product.name }}
                </div>
                <div class="caption-1">
                  {{ lineItems.product.upc }}
                </div>
              </td>
              <td>
                <div class="body-2">Item Price</div>
                <div class="subheading-2">{{ lineItems.price | currency: "IDR" }}</div>
              </td>
              <td>
                <div class="body-2">Total Item</div>
                <div class="subheading-2">{{ lineItems.quantity }}</div>
              </td>
              <td></td>
            </tr>
          </ng-container>
          </tbody>
        </table>
      </ng-container>
      <table class="summary">
        <thead>
          <tr>
            <th colspan="2">
              <h3 class="heading-1">Order Summary</h3>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Total amount cart (before Disc)</td>
            <td class="summary-order-value">{{ orderDetailData.subtotalCost | currency: "IDR" }}</td>
          </tr>
          <tr>
            <td>Discount Total</td>
            <td class="summary-order-value">-{{ orderDetailData.discount | currency: "IDR" }}</td>
          </tr>
          <tr>
            <td>Total amount cart (after Disc)</td>
            <td class="summary-order-value">
              {{ orderDetailData.subtotalCost - orderDetailData.discount | currency: "IDR" }}
            </td>
          </tr>
          <tr>
            <td>Shipping total</td>
            <td class="summary-order-value">{{ orderDetailData.shippingCost | currency: "IDR" }}</td>
          </tr>
          <tr>
            <td>Order total</td>
            <td class="summary-order-value">{{ orderDetailData.orderPayment.amount | currency: "IDR" }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Modals -->
    <nus-transport-to-counter-selection-modal></nus-transport-to-counter-selection-modal>
    <nus-deliver-to-counter-auto-awb-modal></nus-deliver-to-counter-auto-awb-modal>
    <nus-deliver-to-counter-manual-input-awb-modal></nus-deliver-to-counter-manual-input-awb-modal>   
    <nus-set-pickup-service-modal></nus-set-pickup-service-modal>
    <nus-pickup-download-shipping-modal></nus-pickup-download-shipping-modal>
    <nus-pickup-service-info-modal></nus-pickup-service-info-modal>
    <nus-input-awb-modal></nus-input-awb-modal>
    <nus-activity-tracking-modal></nus-activity-tracking-modal>
    `,
  styles: [
    '.wrapper { margin: 16px 0; }',
    'table { margin-bottom: 24px; }',
    'h3 { color: var(--lighten-black); margin-bottom: 0; }',
    '.order-status td { padding: 20px 24px; vertical-align: top; width: 25%; }',
    '.button-status-action { display: flex; align-items: center; gap: 16px; }',
    '.button-status-action button { padding: 0 10px; }',
    '.subheading-2 { color: var(--lighten-black); margin-bottom: 2px; }',
    '.product-list td { padding: 9px 8px; border: none; }',
    '.product-list td:first-child { width: 64px; padding-left: 24px; }',
    '.product-list td:nth-child(2) { width: 390px; }',
    '.product-list td:nth-child(3) { width: 120px; }',
    '.product-list tr:first-child > td { padding: 16px 24px; border-bottom: none }',
    '.summary thead { background: transparent; }',
    '.summary th { padding: 20px 24px; }',
    '.summary td { width: 50%; padding: 14px 24px; }',
    ':host nus-milestone { width: 180px; }',
    '.download-button { min-width: 200px; display: block; margin-left: auto; }',
    'img { height: 64px; width: 64px; }',
    '.no-image { background: var(--lighten-black); }'
  ]
})
export class OrderDetailComponent {
  orderDetailData: order.IOrderDetail;
  shipmentMessageInfo: Array<order.IOrderShipmentInfo> = [];
  isShippableOrder = true;
  isDetailShowed = false;
  isRequestShipment = false;

  @ViewChild(TransportToCounterSelectionModalComponent) transferOrderSelection: TransportToCounterSelectionModalComponent;
  @ViewChild(DeliverToCounterAutogeneratedAwbComponent) deliverToCounterAutogeneratedAwb: DeliverToCounterAutogeneratedAwbComponent;
  @ViewChild(DeliverToCounterManualInputAwbComponent) deliverToCounterManualAwb: DeliverToCounterManualInputAwbComponent;
  @ViewChild(SetPickUpServiceComponent) setPickupService: SetPickUpServiceComponent;
  @ViewChild(PickupDownloadShippingModalComponent) pickupDownloadShipping: PickupDownloadShippingModalComponent;
  @ViewChild(PickupServiceInfoModalComponent) pickupServiceInfo: PickupServiceInfoModalComponent;
  @ViewChild(InputAwbModalComponent) inputAwb: InputAwbModalComponent;
  @ViewChild(ActivityTrackingModalComponent) activityTracking: ActivityTrackingModalComponent;

  constructor(public route: ActivatedRoute,
              public service: OrderService,
              public shipmentService: ShipmentService) {
  }

  ngOnInit(): void {
    this.route.data.subscribe((
      data: { entity: order.IOrderDetail, orderStatus: Array<drf.IChoice> }) => {
      this.orderDetailData = data.entity;
      this.isShippableOrder = !!this.orderDetailData.orderAddress;
    });
    this.fetchAwbUrl();
  }

  get currentMilestone(){
    let status = this.orderDetailData.status === 'shipped'? 'ship': this.orderDetailData.status;
    return status;
  }

  getConnote(childrenData: any) {
    if (childrenData.shipmentHistory?.awbNumber) {
      return childrenData.shipmentHistory.awbNumber;
    }
    return '';
  }

  fetchAwbUrl(selectedOrderDetail?: any) {
    if (!selectedOrderDetail) {
      this.orderDetailData.children.forEach((children) => {
        children.data.forEach((childrenData) => {
          if (childrenData.shipmentHistory?.href) {
            this.shipmentService.fetch(getSlugFromHref(childrenData.shipmentHistory?.href)).subscribe((entity) => {
              childrenData.shipmentHistory.shippingLabelUrl = entity.shippingLabelUrl;
            });
          }

        });
      });
    } else {
      this.shipmentService.fetch(getSlugFromHref(selectedOrderDetail.shipmentHistory.href)).subscribe((entity) => {
        selectedOrderDetail.shipmentHistory.shippingLabelUrl = entity.shippingLabelUrl;
      });
    }
  }

  printConnote(labelUrl: string) {
    let windowContent = '<!DOCTYPE html>';
    windowContent += '<html>';
    windowContent += '<head><title>Print</title></head>';
    windowContent += '<body>';
    windowContent += '<img src="' + labelUrl + '">';
    windowContent += '</body>';
    windowContent += '</html>';

    const printWin = window.open('', '', 'width=' + screen.availWidth + ',height=' + screen.availHeight);
    printWin.document.open();
    printWin.document.write(windowContent);

    printWin.document.addEventListener('load', () => {
      printWin.focus();
      printWin.print();
      printWin.document.close();
      printWin.close();
    }, true);
  }

  /**
   * Check manual transfer or not
   */
  isManualTransfer(orderData: order.IOrderDetail): boolean {
    return orderData?.orderPayment?.paymentGateway.type === 'manual_transfer';
  }

  updateOrder(childrenData: any, status: OrderStatusType) {
    const children: Array<string> = [];
    if (status === 'ready' && childrenData.status !== 'paid') {
      alert('Cannot change unpaid order');
    } else if (status === 'shipped' && childrenData.status !== 'ready') {
      alert(`Cannot change order that wasn't ready`);
    } else if (status === 'complete' && childrenData.status !== 'shipped') {
      alert(`Cannot change order that wasn't shipped`);
    } else {
      const entity = {
        orderNumber: childrenData.orderNumber,
        status,
        href: childrenData.href
      };

      this.service.update(entity as any).subscribe((resp) => {
          this.service.fetch(this.orderDetailData.orderNumber).subscribe(
            (response) => {
              // its not correct, IOrder not same as IOrderDetail
              this.orderDetailData = response as any;
              this.fetchAwbUrl();
            },
            (error) => {
              console.log('Error', error);
          });
      }, (error) => {
        console.log('error', error);
      });
    }

  }

  requestShipmentAndUpdateOrder(childrenData: any) {
    if (childrenData.status !== 'ready') {
      alert(`Cannot ship order that wasn't ready`);
    } else if (childrenData.status === 'shipped') {
      alert(`Order already shipped`);
    } else {
      this.isRequestShipment = true;
      let shipmentInfo = {
            orderHref: childrenData.href,
            message: 'Please wait...',
            success: true,
            connoteNumber: '',
          };
      this.shipmentMessageInfo.push(shipmentInfo);
      this.shipmentService.createAWB({
        orderNumber: getSlugFromHref(childrenData.href)
      }).subscribe((response) => {
        const foundShipmentInfoIndex = this.shipmentMessageInfo.findIndex((messageInfo) => {
          return messageInfo.orderHref === childrenData.href;
        });
        if (response instanceof ErrorResult) {
          shipmentInfo = {
            orderHref: childrenData.href,
            message: 'Please contact administrator, something went wrong...',
            success: true,
            connoteNumber: '',
          };
        } else {
          shipmentInfo = {
            orderHref: childrenData.href,
            message: response.messages[0],
            success: response.success,
            connoteNumber: response.entity.airwayBillNumber,
          };
          if (!childrenData.shipmentHistory) {
            childrenData.shipmentHistory = new Object({
              awbNumber: null,
              href: null,
              shippingLabelUrl: '',
            });
          }
          childrenData.shipmentHistory.href = response.entity.href;
          childrenData.shipmentHistory.awbNumber = response.entity.awbNumber;
          this.fetchAwbUrl(childrenData);
          this.updateOrder(childrenData, 'shipped');
        }
        if (foundShipmentInfoIndex !== -1) {
          this.shipmentMessageInfo[foundShipmentInfoIndex] = shipmentInfo;
        } else {
          this.shipmentMessageInfo.push(shipmentInfo);
        }
        this.isRequestShipment = false;
      });
    }
  }

  getShipmentMessageInfo(orderHref: string) {
    if (this.shipmentMessageInfo.length) {
      const shipMessage = this.shipmentMessageInfo.filter(info => info.orderHref === orderHref)[0];
      return shipMessage?.message ?? '';
    }
    return '';
  }

  getIsDisabledForReady(childrenData: any): boolean {
    if (childrenData.status !== 'paid' || childrenData.status === 'ready' || childrenData.status === 'waiting') {
      return true;
    }
    return false;
  }

  getIsDisabledForShipment(childrenData: any): boolean {
    if (childrenData.status !== 'ready' || childrenData.status === 'shipped' || this.isRequestShipment) {
      return true;
    }
    return false;
  }

  getIsDisabledForComplete(childrenData: any): boolean {
    if (childrenData.status !== 'shipped' || childrenData.status === 'complete') {
      return true;
    }
    return false;
  }

  showKirim(orderDetailData: any) {
    if (orderDetailData.shipmentHistory) {
      return false;
    }
    if (this.orderDetailData.orderPayment.status !== 'paid') {
      return false;
    }
    if (this.shipmentMessageInfo.length > 0) {
      const showMessage = this.shipmentMessageInfo.filter(info => info.orderHref === orderDetailData.href)[0];
      return !showMessage?.success;
    }
    return true;
  }
}

