import { Component, OnInit, ViewChild } from '@angular/core';
import { FormBuilder, FormControl } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';

import { AbstractDetailComponent, ErrorResult, getSlugFromHref, ToastService } from '@nusantara/core';
import { 
  UserService,
  ShipmentService,
  OrderService,
  OrderReportService,
  OrderDownloadFileService,
  SvgIconService
} from '@nusantara/services';
import { drf, order, OrderStatusType } from '@nusantara/models';
import { 
  TransportToCounterSelectionModalComponent, 
  PickupDownloadShippingModalComponent, 
  SetPickUpServiceComponent, 
  PickupServiceInfoModalComponent,
  InputAwbModalComponent, 
  DeliverToCounterAutogeneratedAwbComponent,
  DeliverToCounterManualInputAwbComponent,
  ActivityTrackingModalComponent, 
} from './modals';

@Component({
  selector: 'nus-order',
  template: `  
    <h1 class="title-1">Order Detail</h1>
    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="fluid">
    <table class="detail">
      <tbody>
        <tr class="no-border-bottom">
          <td>
            <div class="body-2">Order Number</div>
            <div class="subheading-2">{{ orderDetailData.orderNumber }}</div>
          </td>
          <td>
            <div class="body-2">Time of Order</div>
            <div class="subheading-2">
              {{ orderDetailData.created | date: 'dd/MM/yyyy HH:mm:ss' }}
            </div>
          </td>
          <td>
            <div class="body-2">Platform</div>
            <div class="subheading-2">{{ orderDetailData.source | uppercase }}</div>
          </td>
          <td></td>
        </tr>
        <tr *ngIf="isDetailShowed" class="no-border-bottom more-detail">
          <td>
            <div class="body-2">Customer Name</div>
            <div class="subheading-2">{{ orderDetailData.customer.name }}</div>
          </td>
          <td>
            <div class="body-2">Phone Number</div>
            <div class="subheading-2">{{ orderDetailData.orderAddress.phoneNumber }}</div>
          </td>
          <td>
            <div class="body-2">Email</div>
            <div class="subheading-2">{{ orderDetailData.customer.name }}</div>
          </td>
          <td>
            <div class="body-2">Address</div>
            <div class="subheading-2"> {{ getOrderAddress() }} </div>
          </td>
        </tr>
        <tr class="more-toggle">
          <td colspan="4">
            <a (click)="isDetailShowed = !isDetailShowed;">{{ isDetailShowed? 'Hide' : 'More' }}</a>
          </td>
        </tr>
        <tr>
          <td colspan="5">
            
          </td>
        </tr>
      </tbody>
    </table>
    </form>


    <div class="tab-header">
      <label [ngClass]="{'active': currentTab === 'orderDetail'}" (click)="currentTab = 'orderDetail'">
        <i class="material-icons">analytics</i>
        <input type="radio" id="tab_summary" value="summary"/>
        Order Detail
      </label>

      <label *ngIf="isManualTransfer(orderDetailData)"
            [ngClass]="{'active': currentTab === 'paymentConfirm'}"
            (click)="currentTab = 'paymentConfirm'">
        <i class="material-icons">assignment</i>
        <input type="radio" id="tab_assignment" value="assignment"/>
        Order Confirm
      </label>
    </div>

    <div *ngIf="currentTab === 'orderDetail'" id="orderDetail">
      <ng-container *ngFor="let children of orderDetailData.children">
        <table class="order-status">
          <tbody>
            <tr>
              <td>
                <div class="body-2">Status</div>
                <div class="subheading-2">{{ (orderDetailData.status ? orderDetailData.status : '-') | titlecase }}</div>
              </td>
              <td>
                <div class="body-2">Logistic</div>
                <div class="subheading-2">
                  <ng-container *ngIf="children.data[0]?.shippingMethod">{{ children.data[0].shippingMethod }}</ng-container>
                </div>
              </td>
              <td>
                <div class="body-2">AWB</div>
                <div class="subheading-2">
                  <!-- todo get from shipment API -->
                </div>
              </td>
              <td></td>
            </tr>
            <tr>
              <td colspan="4">
                <span class="button-status-action">
                  <nus-milestone [steps]="['ready', 'ship', 'complete']" [current]="currentMilestone"></nus-milestone>
                  
                  <ng-container *ngIf="canUpdateOrder">
                    <div class="update-dropdown">
                      <select name="status" id="status" [formControl]="status">
                        <option *ngFor="let orderStatus of statusCanUpdateChoices"
                                [ngValue]="orderStatus.value">
                          {{ orderStatus.displayName }}
                        </option>
                      </select>
                      <p *ngIf="status.invalid && (status.touched || status.dirty)"
                        style="margin: 0; color: red; max-width: 200px;">
                        <span *ngIf="status.hasError('server')">{{ status.errors['server'] }}</span>
                        <!-- todo: handle other error need to think again  -->
                      </p>
                    </div>
                  </ng-container>

                  <button *ngIf="orderDetailData.status === 'paid'" type="button" class="control">Ready</button>
                  <button *ngIf="orderDetailData.status === 'ready'" type="button" class="control">Ship</button>
                  <button *ngIf="orderDetailData.status === 'shipped'" type="button" class="control">Complete</button>

                  <!-- <button type="button" class="control secondary" 
                    (click)="activityTracking.open()">
                    View Progress
                    </button>
                  -->

                  <div class="download-button">
                    <button class="download control secondary" mat-button [matMenuTriggerFor]="menu">
                      Download
                      <mat-icon class="icon-secondary" svgIcon="arrow-down"></mat-icon>
                    </button>
                    <mat-menu #menu>
                      <button mat-menu-item (click)="downloadProductList()">Product List</button>
                      <button mat-menu-item 
                        [disabled]="!getConnote(children.data[0])" 
                        (click)="printConnote(children.data[0].shipmentHistory.shippingLabelUrl)">
                        Shipping Label
                      </button>
                    </mat-menu>
                  </div>
                </span>
              </td>
            </tr>
          </tbody>
        </table>

        <table class="product-list">
          <tbody>
          <tr>
            <td colspan="4">
              <h3 class="heading-1">Product</h3>
            </td>
          </tr>
          <ng-container *ngFor="let data of children.data">
            <tr *ngFor="let lineItems of data.lineItems">
              <td>
                <div><img [src]="lineItems.product.image" alt="Product Image"></div>
              </td>
              <td>
                <div class="subheading-2">
                  {{ lineItems.product.name }}
                </div>
                <div class="caption-1">
                  {{ lineItems.product.upc }}
                </div>
              </td>
              <td>
                <div class="body-2">Item Price</div>
                <div class="subheading-2">{{ lineItems.price | currency: "IDR" }}</div>
              </td>
              <td>
                <div class="body-2">Total Item</div>
                <div class="subheading-2">{{ lineItems.quantity }}</div>
              </td>
            </tr>
          </ng-container>
          </tbody>
        </table>
      </ng-container>
      <table class="summary">
        <thead>
          <tr>
            <th colspan="2">
              <h3 class="heading-1">Order Summary</h3>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Total amount cart (before Disc)</td>
            <td class="summary-order-value">{{ orderDetailData.subtotalCost | currency: "IDR" }}</td>
          </tr>
          <tr>
            <td>Discount Total</td>
            <td class="summary-order-value">-{{ orderDetailData.discount | currency: "IDR" }}</td>
          </tr>
          <tr>
            <td>Total amount cart (after Disc)</td>
            <td class="summary-order-value">
              {{ orderDetailData.subtotalCost - orderDetailData.discount | currency: "IDR" }}
            </td>
          </tr>
          <tr>
            <td>Shipping total</td>
            <td class="summary-order-value">{{ orderDetailData.shippingCost | currency: "IDR" }}</td>
          </tr>
          <tr>
            <td>Order total</td>
            <td class="summary-order-value">{{ orderDetailData.orderPayment.amount | currency: "IDR" }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div *ngIf="currentTab === 'paymentConfirm'" id="paymentConfirm" style="margin-bottom: 20px">
      <nus-order-confirm [order]="orderDetailData"></nus-order-confirm>
    </div>

    <button type="button" (click)="navigateToParent(true)" class="control">Back</button>

    <!-- Modals -->
    <nus-transport-to-counter-selection-modal></nus-transport-to-counter-selection-modal>
    <nus-deliver-to-counter-auto-awb-modal></nus-deliver-to-counter-auto-awb-modal>
    <nus-deliver-to-counter-manual-input-awb-modal></nus-deliver-to-counter-manual-input-awb-modal>   
    <nus-set-pickup-service-modal></nus-set-pickup-service-modal>
    <nus-pickup-download-shipping-modal></nus-pickup-download-shipping-modal>
    <nus-pickup-service-info-modal></nus-pickup-service-info-modal>
    <nus-input-awb-modal></nus-input-awb-modal>
    <nus-activity-tracking-modal></nus-activity-tracking-modal>
    `,
  styles: [
    'table { margin-bottom: 24px; }',
    'h3 { color: var(--lighten-black); margin-bottom: 0; }',
    'textarea { width: 100%; }',
    '.detail td, .order-status td { padding: 20px 24px; vertical-align: top; width: 25%; }',
    '.detail tr.no-border-bottom td { border-bottom: none; }',
    '.detail tr.more-detail td { padding-top: 3px; }',
    '.detail tr.more-toggle td { padding: 0 24px 18px; }',
    '.update-dropdown > select { min-width: 220px; }',
    '.button-status-action { display: flex; justify-content: flex-start; gap: 16px; }',
    '.button-status-action button { padding: 0 10px; }',
    '.subheading-2 { color: var(--lighten-black); margin-bottom: 2px; }',
    '.product-list td { padding: 9px 8px; border: none; }',
    '.product-list td:first-child { width: 64px; padding-left: 24px; }',
    '.product-list tr:first-child > td { padding: 16px 24px; border-bottom: none }',
    '.summary thead { background: transparent; }',
    '.summary th { padding: 20px 24px; }',
    '.summary td { width: 50%; padding: 14px 24px; }',
    ':host nus-milestone { width: 180px; }',
    '.tab-header label.active { color: var(--secondary); }', 
    '.tab-header input:checked { background-color: var(--secondary); }',
    '.tab-header { margin-bottom: 20px; }', 
    '.tab-header i { display: block; }', 
    '.tab-header input[type=radio] { display: none; }',
    `.tab-header label {
        display: inline-block; 
        border-bottom: 2px solid;
        text-align: center;
        padding: 0 10px;
    }`,
    '.download-button { margin-left: auto; }',
    '::ng-deep .icon-secondary svg { fill: var(--secondary); }',
    'img { height: 64px; width: 64px; }',
    ''
  ]
})
export class OrderComponent extends AbstractDetailComponent<order.IOrderDetail> implements OnInit {

  orderDetailData: order.IOrderDetail;
  shipmentMessageInfo: Array<order.IOrderShipmentInfo> = [];
  currentTab: 'orderDetail' | 'paymentConfirm' = 'orderDetail';
  orderStatusChoices: Array<drf.IChoice>;
  entity: order.IOrderDetail;
  isRequestShipment = false;
  isShippableOrder = true;
  isDetailShowed = false;

  @ViewChild(TransportToCounterSelectionModalComponent) transferOrderSelection: TransportToCounterSelectionModalComponent;
  @ViewChild(DeliverToCounterAutogeneratedAwbComponent) deliverToCounterAutogeneratedAwb: DeliverToCounterAutogeneratedAwbComponent;
  @ViewChild(DeliverToCounterManualInputAwbComponent) deliverToCounterManualAwb: DeliverToCounterManualInputAwbComponent;
  @ViewChild(SetPickUpServiceComponent) setPickupService: SetPickUpServiceComponent;
  @ViewChild(PickupDownloadShippingModalComponent) pickupDownloadShipping: PickupDownloadShippingModalComponent;
  @ViewChild(PickupServiceInfoModalComponent) pickupServiceInfo: PickupServiceInfoModalComponent;
  @ViewChild(InputAwbModalComponent) inputAwb: InputAwbModalComponent;
  @ViewChild(ActivityTrackingModalComponent) activityTracking: ActivityTrackingModalComponent;

  constructor(public service: OrderService,
              public route: ActivatedRoute,
              public router: Router,
              public toast: ToastService,
              public userService: UserService,
              public shipmentService: ShipmentService,
              private fb: FormBuilder,
              private orderReportService: OrderReportService,
              private orderDonwloadService: OrderDownloadFileService,
              svgIconService: SvgIconService) {
    super(route, router, toast, service);
    svgIconService.registerIcons();
  }

  ngOnInit(): void {
    super.ngOnInit();
    this.route.data.subscribe((
      data: { entity: order.IOrderDetail, orderStatus: Array<drf.IChoice> }) => {
      this.orderDetailData = data.entity;
      this.orderStatusChoices = data.orderStatus;
      this.isShippableOrder = !!this.orderDetailData.orderAddress;
    });
    this.fetchAwbUrl();
  }

  initializeForm(entity?: order.IOrderDetail) {
    this.form = this.fb.group({
      status: [entity?.status ?? 'unpaid', []],
    });
    this.entity = entity;
  }

  get status(): FormControl { return this.form.get('status') as FormControl; }

  get currentMilestone(){
    let status = this.orderDetailData.status === 'shipped'? 'ship': this.orderDetailData.status;
    return status;
  }

  onSubmit(): void {
    if (this.form.valid) {
      this.service.updateByOrderNumber(this.entity.orderNumber, this.form.value).subscribe(() => {
        alert('success update order');
        this.router.navigate([]);
      }, error => this._handleError(error));
    }
  }

  _handleError(error: any) {
    if (error.status === 400) {
      this.setErrorsMessage(error.error);
    }
  }

  setErrorsMessage(error: any) {
    Object.keys(error).forEach((fieldName: any) => {
      if (this.form.controls[fieldName]) {
        this.form.controls[fieldName].setErrors({server: error[fieldName]});
      }
    });
  }

  showKirim(orderDetailData: any) {
    if (orderDetailData.shipmentHistory) {
      return false;
    }
    if (this.orderDetailData.orderPayment.status !== 'paid') {
      return false;
    }
    if (this.shipmentMessageInfo.length > 0) {
      const showMessage = this.shipmentMessageInfo.filter(info => info.orderHref === orderDetailData.href)[0];
      return !showMessage?.success;
    }
    return true;
  }

  requestShipmentAndUpdateOrder(childrenData: any) {
    if (childrenData.status !== 'ready') {
      alert(`Cannot ship order that wasn't ready`);
    } else if (childrenData.status === 'shipped') {
      alert(`Order already shipped`);
    } else {
      this.isRequestShipment = true;
      let shipmentInfo = {
            orderHref: childrenData.href,
            message: 'Please wait...',
            success: true,
            connoteNumber: '',
          };
      this.shipmentMessageInfo.push(shipmentInfo);
      this.shipmentService.createAWB({
        orderNumber: getSlugFromHref(childrenData.href)
      }).subscribe((response) => {
        const foundShipmentInfoIndex = this.shipmentMessageInfo.findIndex((messageInfo) => {
          return messageInfo.orderHref === childrenData.href;
        });
        if (response instanceof ErrorResult) {
          shipmentInfo = {
            orderHref: childrenData.href,
            message: 'Please contact administrator, something went wrong...',
            success: true,
            connoteNumber: '',
          };
        } else {
          shipmentInfo = {
            orderHref: childrenData.href,
            message: response.messages[0],
            success: response.success,
            connoteNumber: response.entity.airwayBillNumber,
          };
          if (!childrenData.shipmentHistory) {
            childrenData.shipmentHistory = new Object({
              awbNumber: null,
              href: null,
              shippingLabelUrl: '',
            });
          }
          childrenData.shipmentHistory.href = response.entity.href;
          childrenData.shipmentHistory.awbNumber = response.entity.awbNumber;
          this.fetchAwbUrl(childrenData);
          this.updateOrder(childrenData, 'shipped');
        }
        if (foundShipmentInfoIndex !== -1) {
          this.shipmentMessageInfo[foundShipmentInfoIndex] = shipmentInfo;
        } else {
          this.shipmentMessageInfo.push(shipmentInfo);
        }
        this.isRequestShipment = false;
      });
    }
  }

  getShipmentMessageInfo(orderHref: string) {
    if (this.shipmentMessageInfo.length) {
      const shipMessage = this.shipmentMessageInfo.filter(info => info.orderHref === orderHref)[0];
      return shipMessage?.message ?? '';
    }
    return '';
  }

  getConnote(childrenData: any) {
    if (childrenData.shipmentHistory?.awbNumber) {
      return childrenData.shipmentHistory.awbNumber;
    }
    return '';
  }

  fetchAwbUrl(selectedOrderDetail?: any) {
    if (!selectedOrderDetail) {
      this.orderDetailData.children.forEach((children) => {
        children.data.forEach((childrenData) => {
          if (childrenData.shipmentHistory?.href) {
            this.shipmentService.fetch(getSlugFromHref(childrenData.shipmentHistory?.href)).subscribe((entity) => {
              childrenData.shipmentHistory.shippingLabelUrl = entity.shippingLabelUrl;
            });
          }

        });
      });
    } else {
      this.shipmentService.fetch(getSlugFromHref(selectedOrderDetail.shipmentHistory.href)).subscribe((entity) => {
        selectedOrderDetail.shipmentHistory.shippingLabelUrl = entity.shippingLabelUrl;
      });
    }
  }

  printConnote(labelUrl: string) {
    let windowContent = '<!DOCTYPE html>';
    windowContent += '<html>';
    windowContent += '<head><title>Print</title></head>';
    windowContent += '<body>';
    windowContent += '<img src="' + labelUrl + '">';
    windowContent += '</body>';
    windowContent += '</html>';

    const printWin = window.open('', '', 'width=' + screen.availWidth + ',height=' + screen.availHeight);
    printWin.document.open();
    printWin.document.write(windowContent);

    printWin.document.addEventListener('load', () => {
      printWin.focus();
      printWin.print();
      printWin.document.close();
      printWin.close();
    }, true);
  }

  getOrderAddress(): string {
    if (!this.orderDetailData || !this.orderDetailData.orderAddress) {
      return '';
    }
    return `${this.orderDetailData.orderAddress.shipToName} ` +
      `${this.orderDetailData.orderAddress.street} ` +
      `${this.orderDetailData.orderAddress.city} ` +
      `${this.orderDetailData.orderAddress.state} ` +
      `${this.orderDetailData.orderAddress.zipcode}`;
  }

  updateOrder(childrenData: any, status: OrderStatusType) {
    const children: Array<string> = [];
    if (status === 'ready' && childrenData.status !== 'paid') {
      alert('Cannot change unpaid order');
    } else if (status === 'shipped' && childrenData.status !== 'ready') {
      alert(`Cannot change order that wasn't ready`);
    } else if (status === 'complete' && childrenData.status !== 'shipped') {
      alert(`Cannot change order that wasn't shipped`);
    } else {
      const entity = {
        orderNumber: childrenData.orderNumber,
        status,
        href: childrenData.href
      };

      this.service.update(entity as any).subscribe((resp) => {
          this.service.fetch(this.orderDetailData.orderNumber).subscribe(
            (response) => {
              // its not correct, IOrder not same as IOrderDetail
              this.orderDetailData = response as any;
              this.fetchAwbUrl();
            },
            (error) => {
              console.log('Error', error);
          });
      }, (error) => {
        console.log('error', error);
      });
    }

  }

  getIsDisabledForReady(childrenData: any): boolean {
    if (childrenData.status !== 'paid' || childrenData.status === 'ready') {
      return true;
    }
    return false;
  }

  getIsDisabledForShipment(childrenData: any): boolean {
    if (childrenData.status !== 'ready' || childrenData.status === 'shipped' || this.isRequestShipment) {
      return true;
    }
    return false;
  }

  getIsDisabledForComplete(childrenData: any): boolean {
    if (childrenData.status !== 'shipped' || childrenData.status === 'complete') {
      return true;
    }
    return false;
  }

  /**
   * Check manual transfer or not
   */
  isManualTransfer(orderData: order.IOrderDetail): boolean {
    return orderData?.orderPayment?.paymentGateway.type === 'manual_transfer';
  }

  /**
   * return status that can `changed`
   */
  get statusCanUpdateChoices(): Array<drf.IChoice> {
    const statusCanUpdate = ['paid', 'cancelled'];
    return this.orderStatusChoices.filter(status => statusCanUpdate.includes(status.value));
  }

  /**
   * check current order status can update or not
   */
  get canUpdateOrder(): boolean {
    const statusCanUpdate = ['unpaid', 'waiting', 'paid', 'cancelled'];
    return (
      this.isManualTransfer(this.orderDetailData) &&
      statusCanUpdate.includes(this.orderDetailData.status)
    );
  } 

  downloadProductList(){
    this.orderReportService.downloadProductDetail(this.orderDetailData.orderNumber).subscribe((response: string) => {
      this.orderDonwloadService.downloadAsCsv(response, 'product-list');
    });
  }
}

