import {
  AfterViewInit,
  Component,
  EventEmitter,
  OnInit,
  Output,
  ViewChild,
} from "@angular/core";
import { ActivatedRoute } from "@angular/router";

import {
  DialogResult,
  ErrorResult,
  getSlugFromHref,
  ToastLevelEnum,
  ToastService,
} from "@nusantara/core";
import { OrderService, ShipmentService } from "@nusantara/services";
import {
  drf,
  IOrderChildrenData,
  order,
  OrderStatusType,
} from "@nusantara/models";
import {
  ActivityTrackingModalComponent,
  DeliverToCounterAutogeneratedAwbComponent,
  DeliverToCounterManualInputAwbComponent,
  InputAwbModalComponent,
  PickupDownloadShippingModalComponent,
  PickupServiceInfoModalComponent,
  SetPickUpServiceComponent,
  TransportToCounterSelectionModalComponent,
} from "./modals";
import { MarketplaceOrderService } from "@nusantara/services/marketplace-order.service";
import { IOrderChildren } from "@nusantara/models/order/order-children";
import {MatDialog} from '@angular/material/dialog';
@Component({
  selector: "nus-order-detail",
  template: `
    <div class="wrapper">
      <ng-container *ngFor="let children of orderDetailData.children">
        <table class="order-status">
          <tbody>
            <tr>
              <td>
                <div class="body-2">Status</div>
                <div class="subheading-2">
                  {{
                    (children.data[0]?.status ? children.data[0]?.status : "-")
                      | titlecase
                  }}
                </div>
              </td>
              <td>
                <div class="body-2">Logistic</div>
                <div class="subheading-2">
                  <ng-container *ngIf="children.data[0]?.shippingMethod">
                    {{
                      children.data[0].shippingMethod
                        ? children.data[0].shippingMethod
                        : "-"
                    }}
                  </ng-container>
                </div>
              </td>
              <td>
                <div class="body-2">AWB</div>
                <div class="subheading-2">
                  <div>
                    {{
                      getAwbNumber(children.data[0])
                        ? getAwbNumber(children.data[0])
                        : "-"
                    }}
                    <a
                      class="refresh-awb"
                      *ngIf="isRefreshAwbEnable(children.data[0])"
                      (click)="refreshAwb()"
                      >Refresh AWB</a
                    >
                  </div>
                </div>
              </td>
              <td>
                <ng-container *ngIf="isManualTransfer(orderDetailData)">
                  <div class="body-2">Warehouse</div>
                  <div class="subheading-2">
                    {{ children.warehouse.name }}
                  </div>
                </ng-container>
              </td>
              <td></td>
            </tr>
            <tr>
              <td colspan="5" class="status-action-row">
                <span class="button-status-action">
                  <nus-milestone
                    [steps]="['ready', 'ship', 'complete']"
                    [current]="getcurrentMilestone(children.data[0]?.status)"
                    [isCompleted]="
                      getcurrentMilestone(children.data[0]?.status) ===
                      'complete'
                    "
                  >
                  </nus-milestone>

                  <ng-container *ngIf="isShippableOrder">
                    <button
                      *ngIf="!isReadyButtonHidden(children.data[0])"
                      type="button"
                      class="control"
                      (click)="updateOrder(children.data[0], 'ready')"
                      [disabled]="isReadyButtonDisabled(children.data[0])"
                    >
                      Ready
                    </button>
                    <button
                      *ngIf="!isShipButtonHidden(children.data[0]) && orderDetailData.sourceName!='shopee' "
                      type="button"
                      class="control"
                      (click)="requestShipmentAndUpdateOrder(children.data[0])"
                    >
                      Ship
                    </button>
                    <button
                      *ngIf="!isShipButtonHidden(children.data[0]) && orderDetailData.sourceName=='shopee' "
                      type="button"
                      class="control"
                      (click)="openTransferModal()"
                    >
                      Ship
                    </button>
                    <button
                      *ngIf="!isShipButtonHidden(children.data[0])"
                      type="button"
                      class="control"
                      [disabled]="!isManagedAwb"
                      (click)="manualShipment(children.data[0])"
                    >
                      Manual Shipment
                    </button>
                    <button
                      *ngIf="!isCompleteButtonHidden(children.data[0])"
                      type="button"
                      class="control"
                      (click)="updateOrder(children.data[0], 'complete')"
                      [disabled]="isCompleteButtonDisabled(children.data[0])"
                    >
                      Complete
                    </button>

                    <a
                      *ngIf="isRedirectMarketplaceShowed(children.data[0])"
                      class="control see-order"
                      href="{{ children.data[0].marketplaceRedirectHref }}"
                      target="_blank"
                    >
                      See Order
                    </a>

                    <!-- <button type="button" class="control secondary"
                      (click)="activityTracking.open()">
                      View Progress
                      </button>
                    -->

                    <div *ngIf="isRedirectMarketplaceShowed(children.data[0])">
                      Orders can only be processed on the
                      {{ orderDetailData.sourceName | titlecase }} Dashboard.
                    </div>
                    <div *ngIf="isCompleteButtonDisabled(children.data[0])">
                      Order will automatically complete when customer receives
                      the package
                    </div>
                  </ng-container>

                  <button
                    class="download-button control secondary"
                    [disabled]="!getConnote(children.data[0])"
                    (click)="
                      printConnote(
                        children.data[0].shipmentHistory.shippingLabelUrl
                      )
                    "
                  >
                    Download Shipping Label
                  </button>
                </span>
              </td>
            </tr>
            <tr class="product-title">
              <td colspan="5" class="product-title">
                <h3 class="heading-1">Product</h3>
              </td>
            </tr>
            <ng-container *ngFor="let data of children.data">
              <tr *ngFor="let lineItems of data.lineItems" class="product-item">
                <td colspan="4">
                  <div class="product-item-detail">
                    <span>
                      <div *ngIf="lineItems.product.image; else noImage">
                        <img
                          [src]="lineItems.product.image"
                          alt="Product Image"
                        />
                      </div>
                      <ng-template #noImage>
                        <img
                          class="no-image"
                          src="/assets/no-image_en.png"
                          alt="Product Image"
                        />
                      </ng-template>
                    </span>
                    <span>
                      <div class="subheading-2">
                        {{ lineItems.product.name }}
                      </div>
                      <div class="caption-1">
                        {{ lineItems.product.upc }}
                      </div>
                    </span>
                    <span>
                      <div class="body-2">Item Price</div>
                      <div class="subheading-2">
                        {{ lineItems.price | currency: "IDR" }}
                      </div>
                    </span>
                    <span>
                      <div class="body-2">Total Item</div>
                      <div class="subheading-2">{{ lineItems.quantity }}</div>
                    </span>
                  </div>
                </td>
                <td coslpan="1"></td>
              </tr>
            </ng-container>
          </tbody>
        </table>
      </ng-container>

      <table class="summary">
        <thead>
          <tr>
            <th colspan="2">
              <h3 class="heading-1">Order Summary</h3>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Total amount cart (before Disc)</td>
            <td class="summary-order-value">
              {{ orderDetailData.subtotalCost | currency: "IDR" }}
            </td>
          </tr>
          <tr>
            <td>Discount Total</td>
            <td class="summary-order-value">
              -{{ orderDetailData.discount | currency: "IDR" }}
            </td>
          </tr>
          <tr>
            <td>Total amount cart (after Disc)</td>
            <td class="summary-order-value">
              {{
                orderDetailData.subtotalCost - orderDetailData.discount
                  | currency: "IDR"
              }}
            </td>
          </tr>
          <tr>
            <td>Shipping total</td>
            <td class="summary-order-value">
              {{ orderDetailData.shippingCost | currency: "IDR" }}
            </td>
          </tr>
          <tr>
            <td>Order total</td>
            <td class="summary-order-value">
              {{ orderDetailData.orderPayment.amount | currency: "IDR" }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Modals -->

    <nus-deliver-to-counter-auto-awb-modal></nus-deliver-to-counter-auto-awb-modal>
    <nus-deliver-to-counter-manual-input-awb-modal></nus-deliver-to-counter-manual-input-awb-modal>
    <nus-set-pickup-service-modal></nus-set-pickup-service-modal>
    <nus-pickup-download-shipping-modal></nus-pickup-download-shipping-modal>
    <nus-pickup-service-info-modal></nus-pickup-service-info-modal>
    <nus-input-awb-modal></nus-input-awb-modal>
    <nus-activity-tracking-modal></nus-activity-tracking-modal>
  `,
  styles: [
    ".wrapper { margin: 16px 0; }",
    "table { margin-bottom: 24px; }",
    "h3 { color: var(--lighten-black); margin-bottom: 0; }",
    ".order-status td { padding: 20px 24px; vertical-align: top; width: 20%; }",
    ".status-action-row { padding-left: 10px !important; }",
    ".button-status-action { display: flex; align-items: center; gap: 16px; }",
    ".button-status-action button { padding: 0 10px; }",
    ".subheading-2 { color: var(--lighten-black); margin-bottom: 2px; }",
    ".product-item td { border-bottom: none; padding: 8px 24px; }",
    ".product-item-detail { display: flex; gap: 16px; align-items: center; }",
    ".product-item-detail > span:first-child { width: 64px; }",
    ".product-item-detail > span:nth-child(2) { min-width: 240px; flex-basis: 390px;}",
    ".product-item-detail > span:nth-child(3) { min-width: 120px; flex-basis: 200px; }",
    ".product-item-detail .caption-1 { overflow: hidden; text-overflow: ellipsis; }",
    "tr.product-title > td { padding: 16px 24px; border-bottom: none; width: 100%; }",
    ".summary thead { background: transparent; }",
    ".summary th { padding: 20px 24px; }",
    ".summary td { width: 50%; padding: 14px 24px; }",
    ":host nus-milestone { width: 180px; }",
    ".download-button { min-width: 200px; display: block; margin-left: auto; }",
    "img { height: 64px; width: 64px; }",
    ".no-image { background: var(--lighten-black); }",
    ".see-order { text-align: center; padding-top: 4px; }",
    ".refresh-awb { margin-left: 5px; font-weight: normal; }",
  ],
})
export class OrderDetailComponent implements OnInit, AfterViewInit {
  @ViewChild(DeliverToCounterAutogeneratedAwbComponent)
  deliverToCounterAutogeneratedAwb: DeliverToCounterAutogeneratedAwbComponent;
  @ViewChild(DeliverToCounterManualInputAwbComponent)
  deliverToCounterManualAwb: DeliverToCounterManualInputAwbComponent;
  @ViewChild(SetPickUpServiceComponent)
  setPickupService: SetPickUpServiceComponent;
  @ViewChild(PickupDownloadShippingModalComponent)
  pickupDownloadShipping: PickupDownloadShippingModalComponent;
  @ViewChild(PickupServiceInfoModalComponent)
  pickupServiceInfo: PickupServiceInfoModalComponent;
  @ViewChild(InputAwbModalComponent) inputAwb: InputAwbModalComponent;
  @ViewChild(ActivityTrackingModalComponent)
  activityTracking: ActivityTrackingModalComponent;

  @Output() enableCancelOrder = new EventEmitter<boolean>(false);
  @Output() updateOrderStatus = new EventEmitter();

  orderDetailData: order.IOrderDetail;
  isShippableOrder = true;
  isDetailShowed = false;
  isRequestShipment = false;

  // marketplace source name that not using default AWB handler
  notManagedAwbSources = ["tokopedia", "lazada", "shopee", "bukalapak"];

  // enable refresh AWB for following source name
  enableRefreshAwb = ["tokopedia", "shopee", "bukalapak"];

  constructor(
    public route: ActivatedRoute,
    public service: OrderService,
    public mpService: MarketplaceOrderService,
    public shipmentService: ShipmentService,
    private dialog: MatDialog,
    private toast: ToastService
  ) {}

  ngOnInit(): void {
    this.route.data.subscribe(
      (data: {
        entity: order.IOrderDetail;
        orderStatus: Array<drf.IChoice>;
      }) => {
        this.orderDetailData = data.entity;
        this.isShippableOrder = !!this.orderDetailData.orderAddress;
      }
    );

    // For managed AWB only, AWB that not synced ex: from various marketplace that not supported
    if (this.isManagedAwb) {
      this.fetchAwbUrl();
    }
  }

  getcurrentMilestone(status: string) {
    return status === "shipped" ? "ship" : status;
  }

  getAwbNumber(childrenData: any) {
    // Applied for all
    if (childrenData.shipmentHistory?.awbNumber) {
      return childrenData.shipmentHistory.awbNumber;
    }
    return "";
  }

  getConnote(childrenData: any) {
    // Exclude this action for not managed AWB
    if (childrenData.shipmentHistory?.awbNumber && this.isManagedAwb) {
      return childrenData.shipmentHistory.awbNumber;
    }

    return "";
  }

  fetchAwbUrl(selectedOrderDetail?: any) {
    if (!selectedOrderDetail) {
      this.orderDetailData.children.forEach((children) => {
        children.data.forEach((childrenData) => {
          if (childrenData.shipmentHistory?.href) {
            this.shipmentService
              .fetch(getSlugFromHref(childrenData.shipmentHistory?.href))
              .subscribe((entity) => {
                childrenData.shipmentHistory.shippingLabelUrl =
                  entity.shippingLabelUrl;
              });
          }
        });
      });
    } else {
      this.shipmentService
        .fetch(getSlugFromHref(selectedOrderDetail.shipmentHistory.href))
        .subscribe((entity) => {
          selectedOrderDetail.shipmentHistory.shippingLabelUrl =
            entity.shippingLabelUrl;
        });
    }
  }

  printConnote(labelUrl: string) {
    let windowContent = "<!DOCTYPE html>";
    windowContent += "<html>";
    windowContent += "<head><title>Print</title></head>";
    windowContent += "<body>";
    windowContent += '<img src="' + labelUrl + '">';
    windowContent += "</body>";
    windowContent += "</html>";

    const printWin = window.open(
      "",
      "",
      "width=" + screen.availWidth + ",height=" + screen.availHeight
    );
    printWin.document.open();
    printWin.document.write(windowContent);

    printWin.document.addEventListener(
      "load",
      () => {
        printWin.focus();
        printWin.print();
        printWin.document.close();
        printWin.close();
      },
      true
    );
  }

  /**
   * Check manual transfer or not
   */
  isManualTransfer(orderData: order.IOrderDetail): boolean {
    return orderData?.orderPayment?.paymentGateway.type === "manual_transfer";
  }

  updateOrder(childrenData: any, status: OrderStatusType) {
    if (status === "ready" && childrenData.status !== "paid") {
      alert("Cannot change unpaid order");
    } else if (status === "shipped" && childrenData.status !== "ready") {
      alert(`Cannot change order that wasn't ready`);
    } else if (status === "complete" && childrenData.status !== "shipped") {
      alert(`Cannot change order that wasn't shipped`);
    } else {
      const entity = {
        orderNumber: childrenData.orderNumber,
        status,
        href: childrenData.href,
      };

      this.service.update(entity as any).subscribe(
        (resp) => {
          this.service.fetch(this.orderDetailData.orderNumber).subscribe(
            (response) => {
              this.orderDetailData = response as any;

              // for non managed AWB option don't fetch awb
              if (this.isManagedAwb) {
                this.fetchAwbUrl();
              }

              // hide cancel order
              if (this.isCancelOrderSupported) {
                this.updateCanCancelOrder();
              }

              this.updateOrderStatus.emit();
            },
            (error) => {
              console.log("Error", error);
            }
          );
        },
        (error) => {
          console.log("error", error);
        }
      );
    }
  }

  requestShipmentAndUpdateOrder(childrenData: any) {
    if (childrenData.status !== "ready") {
      alert(`Cannot ship order that wasn't ready`);
    } else if (childrenData.status === "shipped") {
      alert(`Order already shipped`);
    } else {
      if (this.isManagedAwb) {
        this.isRequestShipment = true;
        this.shipmentService
          .createAWB({
            orderNumber: getSlugFromHref(childrenData.href),
          })
          .subscribe((response) => {
            if (response instanceof ErrorResult) {
              this.toast?.addMessage(
                "Please try again or contact the administrator.",
                "Unable to Proceed",
                ToastLevelEnum.error
              );
            } else {
              if (!childrenData.shipmentHistory) {
                childrenData.shipmentHistory = new Object({
                  awbNumber: null,
                  href: null,
                  shippingLabelUrl: "",
                });
              }
              this.fetchAwbUrl(childrenData);
              this.updateOrder(childrenData, "shipped");
            }
            this.isRequestShipment = false;
          });
      } else {
        // non managed AWB
        this.updateOrder(childrenData, "shipped");
      }
    }
  }

  isReadyButtonDisabled(childrenData: any): boolean {
    return childrenData === "unpaid";
  }

  isReadyButtonHidden(childrenData: any): boolean {
    if (
      childrenData.status !== "paid" ||
      childrenData.status === "ready" ||
      childrenData.status === "waiting"
    ) {
      return true;
    }
    return false;
  }

  isShipButtonHidden(childrenData: any): boolean {
    if (
      childrenData.status !== "ready" ||
      childrenData.status === "shipped" ||
      this.isRequestShipment
    ) {
      return true;
    }
    return false;
  }

  isCompleteButtonHidden(childrenData: any): boolean {
    if (
      childrenData.status !== "shipped" ||
      childrenData.status === "complete" ||
      this.isRedirectMarketplaceShowed(childrenData)
    ) {
      return true;
    }
    return false;
  }

  // trigger cancel button on main order page
  updateCanCancelOrder() {
    if (["unpaid", "waiting", "ready"].includes(this.orderDetailData.status)) {
      this.enableCancelOrder.emit(true);
    } else {
      this.enableCancelOrder.emit(false);
    }
  }

  manualShipment(iOrderChildrenDatum: IOrderChildrenData) {
    this.inputAwb.open();
    this.inputAwb.orderNumber.setValue(
      getSlugFromHref(iOrderChildrenDatum.href)
    );
  }

  ngAfterViewInit(): void {
    this.inputAwb.onClose.subscribe(() => this.inputAwbClose());
  }

  private inputAwbClose() {
    if (this.inputAwb.result === DialogResult.OK) {
      const awbNumber = this.inputAwb.awbNumber.value;
      if (this.inputAwb.form.valid) {
        this.shipmentService
          .manualAWB({
            orderNumber: this.inputAwb.orderNumber.value,
            awbNumber,
          })
          .subscribe((response) => {
            if (response instanceof ErrorResult) {
              this.toast?.addMessage(
                "Please try again or contact the administrator.",
                "Unable to Proceed",
                ToastLevelEnum.error
              );
            } else {
              this.orderDetailData.children.forEach((children) => {
                children.data.forEach((childrenData) => {
                  if (
                    getSlugFromHref(childrenData.href) ===
                    this.inputAwb.orderNumber.value
                  ) {
                    if (!childrenData.shipmentHistory) {
                      childrenData.shipmentHistory = {
                        awbNumber: null,
                        href: null,
                        shippingLabelUrl: "",
                      };
                    }
                    this.fetchAwbUrl(childrenData);
                    this.updateOrder(childrenData, "shipped");
                  }
                });
              });
            }
            this.isRequestShipment = false;
          });
      } else {
        this.toast?.addMessage(
          "Your AWB entry is not valid.",
          "Unable to Proceed",
          ToastLevelEnum.error
        );
      }
    }
  }

  get isManagedAwb() {
    return !(
      this.orderDetailData.source == "marketplace" &&
      this.notManagedAwbSources.includes(this.orderDetailData.sourceName)
    );
  }

  get isCancelOrderSupported() {
    return !(
      ["web", "pos"].includes(this.orderDetailData.source) ||
      this.orderDetailData.sourceName == "tsc"
    );
  }

  // after click ship, redirect to marketplace admin
  // for status : shipped and source name : bukalapak/tokped/shopee
  get isfulfillmentException() {
    return (
      this.enableRefreshAwb.includes(this.orderDetailData.sourceName) &&
      this.orderDetailData.status === "shipped"
    );
  }

  isRefreshAwbEnable(childrenData: IOrderChildrenData) {
    return this.isfulfillmentException && !this.getAwbNumber(childrenData);
  }

  isRedirectMarketplaceShowed(childrenData: IOrderChildrenData) {
    return (
      this.isfulfillmentException &&
      childrenData.marketplaceRedirectHref !== null &&
      !this.getAwbNumber(childrenData)
    );
  }

  isCompleteButtonDisabled(childrenData: IOrderChildrenData) {
    return this.isfulfillmentException && !!this.getAwbNumber(childrenData);
  }

  refreshAwb() {
    this.mpService
      .fetchDetail(this.orderDetailData.orderNumber)
      .subscribe((_) => {
        window.location.reload();
      });
  }

  openTransferModal(){
    this.mpService
      .fetchLogisticInfo(this.orderDetailData.orderNumber, this.orderDetailData.storeId)
      .subscribe((response) => {
          if(response.type.length!=0){
            this.dialog.open(TransportToCounterSelectionModalComponent, {
              data: {"logistic": response, "orderDetail": this.orderDetailData},
              width: "540px",
              height: "640px",
            });
          }
      });
  }
}
