import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { SharedModule } from '@nusantara/shared';
import { FulfillmentRoutingModule } from './fulfillment-routing.module';
import {
  OrderListComponent,
  OrderComponent,
  OrderDetailComponent,
  OrderPaymentConfirmComponent,
  OrderListHeaderComponent,
  OrderDateFilterComponent,
  OrderFiltersComponent,
  OrderCustomPaginationComponent,
  TransportToCounterSelectionModalComponent,
  SetPickUpServiceComponent,
  PickupDownloadShippingModalComponent,
  PickupServiceInfoModalComponent,
  DeliverToCounterAutogeneratedAwbComponent,
  DeliverToCounterManualInputAwbComponent,
  InputAwbModalComponent,
  ActivityTrackingModalComponent,
  PaymentConfirmModalComponent,
  PaymentConfirmFormModalComponent,
  DeleteConfirmDialogComponent,
  CancelOrderDialogComponent,
  MarkAsTestingDialogComponent
} from './orders';
import { NgxSmartModalModule } from 'ngx-smart-modal';
import { MatSelectModule } from '@angular/material/select';
import { MatDatepickerModule} from '@angular/material/datepicker';
import {
  MatNativeDateModule,
  MAT_RIPPLE_GLOBAL_OPTIONS,
} from '@angular/material/core';
import { MatFormFieldModule, MAT_FORM_FIELD_DEFAULT_OPTIONS } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatCheckboxModule } from '@angular/material/checkbox';

@NgModule({
  declarations: [
    OrderListComponent,
    OrderComponent,
    OrderDetailComponent,
    OrderPaymentConfirmComponent,
    OrderListHeaderComponent,
    OrderDateFilterComponent,
    OrderFiltersComponent,
    OrderCustomPaginationComponent,
    TransportToCounterSelectionModalComponent,
    SetPickUpServiceComponent,
    PickupDownloadShippingModalComponent,
    PickupServiceInfoModalComponent,
    DeliverToCounterAutogeneratedAwbComponent,
    DeliverToCounterManualInputAwbComponent,
    InputAwbModalComponent,
    ActivityTrackingModalComponent,
    PaymentConfirmModalComponent,
    PaymentConfirmFormModalComponent,
    DeleteConfirmDialogComponent,
    CancelOrderDialogComponent,
    MarkAsTestingDialogComponent
  ],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    SharedModule,
    FulfillmentRoutingModule,
    NgxSmartModalModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonModule,
    MatMenuModule,
    MatCheckboxModule
  ],
  providers: [
    { provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: { floatLabel: 'never', appearance: 'outline' } },
    { provide: MAT_RIPPLE_GLOBAL_OPTIONS, useValue: { disabled: true } },
  ]
})
export class FulfillmentModule { }
